# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          sudo apt update
          sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat maven

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout d4j
        uses: actions/checkout@v2
        with:
          repository: amir9979/defects4j
          path: .
          fetch-depth: 0
      
      - run: cpanm --installdeps .
      - run: ./init.sh

#       - name: initialize-project-and-collect-issues
#         run: ./initialize-project-and-collect-issues.pl -p Lang -n commons-lang -w bug-mining -r https://github.com/apache/commons-lang.git -g jira -t LANG -e "/(LANG-\d+)/mi"
#         working-directory: ./framework/bug-mining
      
      
#       - name: initialize-revisions
#         run: ./initialize-revisions.pl -p Lang -w bug-mining 
#         working-directory: ./framework/bug-mining

      - name: analyze-project
        run: ./analyze-project.pl -p Lang -w bug-mining -g jira -t LANG
        working-directory: ./framework/bug-mining


      - name: get-trigger
        run: ./get-trigger.pl -p Lang -w bug-mining 
        working-directory: ./framework/bug-mining

      - name: get-metadata
        run: ./get-metadata.pl -p Lang -w bug-mining 
        working-directory: ./framework/bug-mining


      
      - name: Upload bug-mining
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: bug-mining
          # A file, directory or wildcard pattern that describes what to upload
          path: ./framework/bug-mining
